#!/bin/bash

regex="^\[GOJ-\(..*\)\]\[..*|..*\].*$"

function verify_ticket() {
  status=`curl -s -o /dev/null -w '%{http_code}' "https://favro.com/api/v1/cards?cardSequentialId=$1" \
    -H "organizationId: organisation_id" \
    -u "user_id":"token"`
  if [ $status -eq "200" ]; then return 0; else return 1; fi
}

function process_list() {
  while read -r line || [ -n "$line" ]; do
    valid_line=`echo $line | grep -e $regex`
    if [ ! -z "$valid_line" ]; then 
      ticket_id=`echo $line | sed -e "s/$regex/\1/"`
      verify_ticket $ticket_id
      valid_ticket=$?
      if [ "$valid_ticket" -eq "0" ]; then
        exit 0
      else
        echo "error: invalid ticket id: GOJ-"$ticket_id
        exit 1
      fi
    else
      echo "error: invalid commit message: "$line
      echo "sample commit message: [GOJ-288][Ritesh|Surajit] - some message"
      exit 1
    fi
  done
}

git log origin/master..HEAD --pretty=format:%s | process_list

